package Model;
// Generated 13/02/2017 01:11:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private int idCliente;
     private String nombreCliente;
     private String tipoFuncionario;
     private float topeMaximo;
     private float porcentajeDescuento;
     private String fechaCreacion;
     private String fechaModificacion;
     private Set<Movimientos> movimientoses = new HashSet<Movimientos>(0);

    public Clientes() {
    }

	
    public Clientes(int idCliente, String nombreCliente, String tipoFuncionario, float topeMaximo, float porcentajeDescuento) {
        this.idCliente = idCliente;
        this.nombreCliente = nombreCliente;
        this.tipoFuncionario = tipoFuncionario;
        this.topeMaximo = topeMaximo;
        this.porcentajeDescuento = porcentajeDescuento;
    }
    public Clientes(int idCliente, String nombreCliente, String tipoFuncionario, float topeMaximo, float porcentajeDescuento, String fechaCreacion, String fechaModificacion, Set<Movimientos> movimientoses) {
       this.idCliente = idCliente;
       this.nombreCliente = nombreCliente;
       this.tipoFuncionario = tipoFuncionario;
       this.topeMaximo = topeMaximo;
       this.porcentajeDescuento = porcentajeDescuento;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.movimientoses = movimientoses;
    }
   
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public String getNombreCliente() {
        return this.nombreCliente;
    }
    
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }
    public String getTipoFuncionario() {
        return this.tipoFuncionario;
    }
    
    public void setTipoFuncionario(String tipoFuncionario) {
        this.tipoFuncionario = tipoFuncionario;
    }
    public float getTopeMaximo() {
        return this.topeMaximo;
    }
    
    public void setTopeMaximo(float topeMaximo) {
        this.topeMaximo = topeMaximo;
    }
    public float getPorcentajeDescuento() {
        return this.porcentajeDescuento;
    }
    
    public void setPorcentajeDescuento(float porcentajeDescuento) {
        this.porcentajeDescuento = porcentajeDescuento;
    }
    public String getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(String fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(String fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set<Movimientos> getMovimientoses() {
        return this.movimientoses;
    }
    
    public void setMovimientoses(Set<Movimientos> movimientoses) {
        this.movimientoses = movimientoses;
    }




}


