package Model;
// Generated 13/02/2017 01:11:03 PM by Hibernate Tools 4.3.1



/**
 * Movimientos generated by hbm2java
 */
public class Movimientos  implements java.io.Serializable {


     private int idMovimiento;
     private Clientes clientes;
     private float saldoInicial;
     private float debito;
     private float credito;
     private float saldoDisponible;
     private float topeMaximo;
     private float topeMaximo0;
     private int i;
     private int i0;

    public Movimientos() {
    }

    public Movimientos(int idMovimiento, Clientes clientes, float saldoInicial, float debito, float credito, float saldoDisponible) {
       this.idMovimiento = idMovimiento;
       this.clientes = clientes;
       this.saldoInicial = saldoInicial;
       this.debito = debito;
       this.credito = credito;
       this.saldoDisponible = saldoDisponible;
    }

    public Movimientos(Float topeMaximo, int i, int i0, Float topeMaximo0, int idCliente) {
        this.topeMaximo = topeMaximo;
        this.i = i;
        this.i0 = i0;
        this.topeMaximo0 = topeMaximo0;
        this.clientes = clientes;
    }
   
    public int getIdMovimiento() {
        return this.idMovimiento;
    }
    
    public void setIdMovimiento(int idMovimiento) {
        this.idMovimiento = idMovimiento;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public float getSaldoInicial() {
        return this.saldoInicial;
    }
    
    public void setSaldoInicial(float saldoInicial) {
        this.saldoInicial = saldoInicial;
    }
    public float getDebito() {
        return this.debito;
    }
    
    public void setDebito(float debito) {
        this.debito = debito;
    }
    public float getCredito() {
        return this.credito;
    }
    
    public void setCredito(float credito) {
        this.credito = credito;
    }
    public float getSaldoDisponible() {
        return this.saldoDisponible;
    }
    
    public void setSaldoDisponible(float saldoDisponible) {
        this.saldoDisponible = saldoDisponible;
    }

    public float getTopeMaximo() {
        return topeMaximo;
    }

    public void setTopeMaximo(float topeMaximo) {
        this.topeMaximo = topeMaximo;
    }

    public int getI() {
        return i;
    }

    public void setI(int i) {
        this.i = i;
    }

    public int getI0() {
        return i0;
    }

    public void setI0(int i0) {
        this.i0 = i0;
    }




}


