package Model;
// Generated 13/02/2017 01:11:03 PM by Hibernate Tools 4.3.1



/**
 * Puntos generated by hbm2java
 */
public class Puntos  implements java.io.Serializable {


     private int idCliente;
     private String nombreCliente;
     private float hotelV;
     private float gigisUsaquen;
     private float gigisZonaG;
     private float bar440;
     private float blackSheep;
     private float bierMarket;
     private float marquez;
     private float bungalow;
     private float matildeLina;
     private float totalConsumo;

    public Puntos() {
    }

    public Puntos(int idCliente, String nombreCliente, float hotelV, float gigisUsaquen, float gigisZonaG, float bar440, float blackSheep, float bierMarket, float marquez, float bungalow, float matildeLina, float totalConsumo) {
       this.idCliente = idCliente;
       this.nombreCliente = nombreCliente;
       this.hotelV = hotelV;
       this.gigisUsaquen = gigisUsaquen;
       this.gigisZonaG = gigisZonaG;
       this.bar440 = bar440;
       this.blackSheep = blackSheep;
       this.bierMarket = bierMarket;
       this.marquez = marquez;
       this.bungalow = bungalow;
       this.matildeLina = matildeLina;
       this.totalConsumo = totalConsumo;
    }
   
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public String getNombreCliente() {
        return this.nombreCliente;
    }
    
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }
    public float getHotelV() {
        return this.hotelV;
    }
    
    public void setHotelV(float hotelV) {
        this.hotelV = hotelV;
    }
    public float getGigisUsaquen() {
        return this.gigisUsaquen;
    }
    
    public void setGigisUsaquen(float gigisUsaquen) {
        this.gigisUsaquen = gigisUsaquen;
    }
    public float getGigisZonaG() {
        return this.gigisZonaG;
    }
    
    public void setGigisZonaG(float gigisZonaG) {
        this.gigisZonaG = gigisZonaG;
    }
    public float getBar440() {
        return this.bar440;
    }
    
    public void setBar440(float bar440) {
        this.bar440 = bar440;
    }
    public float getBlackSheep() {
        return this.blackSheep;
    }
    
    public void setBlackSheep(float blackSheep) {
        this.blackSheep = blackSheep;
    }
    public float getBierMarket() {
        return this.bierMarket;
    }
    
    public void setBierMarket(float bierMarket) {
        this.bierMarket = bierMarket;
    }
    public float getMarquez() {
        return this.marquez;
    }
    
    public void setMarquez(float marquez) {
        this.marquez = marquez;
    }
    public float getBungalow() {
        return this.bungalow;
    }
    
    public void setBungalow(float bungalow) {
        this.bungalow = bungalow;
    }
    public float getMatildeLina() {
        return this.matildeLina;
    }
    
    public void setMatildeLina(float matildeLina) {
        this.matildeLina = matildeLina;
    }
    public float getTotalConsumo() {
        return this.totalConsumo;
    }
    
    public void setTotalConsumo(float totalConsumo) {
        this.totalConsumo = totalConsumo;
    }




}


