package Model;
// Generated 13/02/2017 01:11:03 PM by Hibernate Tools 4.3.1



/**
 * Transacciones generated by hbm2java
 */
public class Transacciones  implements java.io.Serializable {


     private int idTransaccion;
     private String nombreCliente;
     private int idPunto;
     private String punto;
     private String fecha;
     private String hora;
     private int idProducto;
     private String descProducto;
     private int cantidad;
     private float valorNeto;
     private float valorDesc;
     private float porcentajeDesc;
     private float totalConsumo;
     private String cajero;
     private String mesero;
     private String numDocumento;
     private String tipoDocumento;
     private String numLicencia;
     private String fechaTransaccion;
     private String tipoFuncionario;
     private float topeMax;

    public Transacciones() {
    }

	
    public Transacciones(int idTransaccion, String nombreCliente, int idPunto, String punto, int idProducto, String descProducto, int cantidad, float valorNeto, float valorDesc, float porcentajeDesc, float totalConsumo, String cajero, String mesero, String numDocumento, String tipoDocumento, String numLicencia, String tipoFuncionario, float topeMax) {
        this.idTransaccion = idTransaccion;
        this.nombreCliente = nombreCliente;
        this.idPunto = idPunto;
        this.punto = punto;
        this.idProducto = idProducto;
        this.descProducto = descProducto;
        this.cantidad = cantidad;
        this.valorNeto = valorNeto;
        this.valorDesc = valorDesc;
        this.porcentajeDesc = porcentajeDesc;
        this.totalConsumo = totalConsumo;
        this.cajero = cajero;
        this.mesero = mesero;
        this.numDocumento = numDocumento;
        this.tipoDocumento = tipoDocumento;
        this.numLicencia = numLicencia;
        this.tipoFuncionario = tipoFuncionario;
        this.topeMax = topeMax;
    }
    public Transacciones(int idTransaccion, String nombreCliente, int idPunto, String punto, String fecha, String hora, int idProducto, String descProducto, int cantidad, float valorNeto, float valorDesc, float porcentajeDesc, float totalConsumo, String cajero, String mesero, String numDocumento, String tipoDocumento, String numLicencia, String fechaTransaccion, String tipoFuncionario, float topeMax) {
       this.idTransaccion = idTransaccion;
       this.nombreCliente = nombreCliente;
       this.idPunto = idPunto;
       this.punto = punto;
       this.fecha = fecha;
       this.hora = hora;
       this.idProducto = idProducto;
       this.descProducto = descProducto;
       this.cantidad = cantidad;
       this.valorNeto = valorNeto;
       this.valorDesc = valorDesc;
       this.porcentajeDesc = porcentajeDesc;
       this.totalConsumo = totalConsumo;
       this.cajero = cajero;
       this.mesero = mesero;
       this.numDocumento = numDocumento;
       this.tipoDocumento = tipoDocumento;
       this.numLicencia = numLicencia;
       this.fechaTransaccion = fechaTransaccion;
       this.tipoFuncionario = tipoFuncionario;
       this.topeMax = topeMax;
    }
   
    public int getIdTransaccion() {
        return this.idTransaccion;
    }
    
    public void setIdTransaccion(int idTransaccion) {
        this.idTransaccion = idTransaccion;
    }
    public String getNombreCliente() {
        return this.nombreCliente;
    }
    
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }
    public int getIdPunto() {
        return this.idPunto;
    }
    
    public void setIdPunto(int idPunto) {
        this.idPunto = idPunto;
    }
    public String getPunto() {
        return this.punto;
    }
    
    public void setPunto(String punto) {
        this.punto = punto;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }
    public String getDescProducto() {
        return this.descProducto;
    }
    
    public void setDescProducto(String descProducto) {
        this.descProducto = descProducto;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public float getValorNeto() {
        return this.valorNeto;
    }
    
    public void setValorNeto(float valorNeto) {
        this.valorNeto = valorNeto;
    }
    public float getValorDesc() {
        return this.valorDesc;
    }
    
    public void setValorDesc(float valorDesc) {
        this.valorDesc = valorDesc;
    }
    public float getPorcentajeDesc() {
        return this.porcentajeDesc;
    }
    
    public void setPorcentajeDesc(float porcentajeDesc) {
        this.porcentajeDesc = porcentajeDesc;
    }
    public float getTotalConsumo() {
        return this.totalConsumo;
    }
    
    public void setTotalConsumo(float totalConsumo) {
        this.totalConsumo = totalConsumo;
    }
    public String getCajero() {
        return this.cajero;
    }
    
    public void setCajero(String cajero) {
        this.cajero = cajero;
    }
    public String getMesero() {
        return this.mesero;
    }
    
    public void setMesero(String mesero) {
        this.mesero = mesero;
    }
    public String getNumDocumento() {
        return this.numDocumento;
    }
    
    public void setNumDocumento(String numDocumento) {
        this.numDocumento = numDocumento;
    }
    public String getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }
    public String getNumLicencia() {
        return this.numLicencia;
    }
    
    public void setNumLicencia(String numLicencia) {
        this.numLicencia = numLicencia;
    }
    public String getFechaTransaccion() {
        return this.fechaTransaccion;
    }
    
    public void setFechaTransaccion(String fechaTransaccion) {
        this.fechaTransaccion = fechaTransaccion;
    }
    public String getTipoFuncionario() {
        return this.tipoFuncionario;
    }
    
    public void setTipoFuncionario(String tipoFuncionario) {
        this.tipoFuncionario = tipoFuncionario;
    }
    public float getTopeMax() {
        return this.topeMax;
    }
    
    public void setTopeMax(float topeMax) {
        this.topeMax = topeMax;
    }




}


