package Model;
// Generated 13/02/2017 01:11:03 PM by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private int idusuario;
     private String nombre;
     private String clave;
     private String rol;
     private String fechaCreacion;
     private String fechaModificacion;

    public Usuarios() {
    }

	
    public Usuarios(int idusuario, String nombre, String clave, String rol) {
        this.idusuario = idusuario;
        this.nombre = nombre;
        this.clave = clave;
        this.rol = rol;
    }
    public Usuarios(int idusuario, String nombre, String clave, String rol, String fechaCreacion, String fechaModificacion) {
       this.idusuario = idusuario;
       this.nombre = nombre;
       this.clave = clave;
       this.rol = rol;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
    }
   
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public String getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(String fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(String fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


